### ISSUE TITLE
Upgrade to the latest version of react.js and webpack

### ISSUE THREAD

**Issue by stevehu** [networknt/react-schema-form#37]
I have received so many requests offline to upgrade to the latest react.js; however, my schedule is so full at the moment. Can someone help to upgrade? Thanks.

**Comment by stevehu** [comment]
Thanks Paul for your help. Both packages work perfectly and I have published them to the npmjs after brief testing.

**Comment by devel-pa** [comment]
You're welcome :)
I think you forgot to change the `package.json` at least for select to refer to the npm

**Comment by stevehu** [comment]
Sorry @devel-pa. Are you saying to have a link to the npmjs.org in the package.json? I've searched package.json spec and couldn't find anything official. I can put something there as a URL but would like to learn from you if there are any common practices available. Thanks.

**Comment by devel-pa** [comment]
@stevehu I'm saying that you've kept in `package.json`

```
https://github.com/networknt/react-schema-form/blob/master/package.json#L60
```

instead of having

```
"react-schema-form-rc-select": "0.2.0"
```

**Comment by stevehu** [comment]
Thanks Paul. I have updated and published another release. I was looking
into the react-schema-form-rc-select and didn't find anything:)

Best regards,

Steve
